[package]
name = "muta-chain"
version = "0.1.0"
authors = ["yejiayu <yejiayu.fe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
muta = { git = "https://github.com/yejiayu/muta", branch = "muta-crate" }
protocol = { git = "https://github.com/yejiayu/muta", branch = "muta-crate" }

derive_more = "0.15"
runtime = "0.3.0-alpha.7"
runtime-tokio = "0.3.0-alpha.6"

asset = { git = "https://github.com/yejiayu/muta", branch = "muta-crate" }
metadata = { path = "services/metadata" }
service-template = { path = "services/service-template" }

[workspace]
members = [
  "services/metadata",
  "services/service-template",
]
